# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3652812824c573428bc5d646d0fdc2fef22d24f154d71bc0aa8e7e260a2acd1192b3101646a661bc354168667394ea3813aabf6a2cf4d8537245e41d81a94dc8

test:
  secret_key_base: ad9eba996b6393bd1af5a0d90d8768b44a1f5bd1b095118f92f83cb667a6c25d0caf943d01a9eb318e802fca20f096295dce3512feb1fd6d2dae684f6be413c9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
